target-version = "py39"

[lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
preview=true
select = [
  "E301",  # blank line between methods
  "E302",  # blank lines top level
  "E303",  # too many blank lines
  "E305",  # 2 blank lines between functions and classes
  "F841",  # no unused variables
]